# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_linux_swift_5_5:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: swift:5.5
    
    resource_class: small

    steps:
      - checkout
      - run: swift build # Install CocoaPods dependencies
      - run: swift test # Run tests using Fastlane
  build_linux_swift_4_2:
    docker:
      - image: swift:4.2
    
    resource_class: small

    steps:
      - checkout
      - run: swift build # Install CocoaPods dependencies
      - run: swift test # Run tests using Fastlane
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build_linux_swift_4_2
      - build_linux_swift_5_5
